### ISSUE TITLE
Using `on-interaction` first click is not registered

### ISSUE THREAD

**Issue by simplenotezy** [maoberlehner/vue-lazy-hydration#40]
When using `on-interaction` the first click is not registered, so only the second click works. Using mouseover could prevent this.

**Comment by maoberlehner** [comment]
This is the expected behaviour. Because the component is not hydrated initially, the there is no click event listener registered on the component. Only after the the component is hydrated, it does listen for the click event.

If you need your component to listen for click events, you can't use `on-interaction`.
